version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./ConversionRates:/app/currency_converter
    depends_on:
      - db

  frontend:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html